# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDelNamespace < Formula
  desc "kubectl plugin to forcefully delete a kubernetes namespace"
  homepage "https://github.com/DoodleScheduling/kubectl-del-namespace"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.5/kubectl-del-namespace_0.0.5_darwin_arm64.tar.gz"
      sha256 "6a8989b5808338bdf850b5c438a7f98086b493e90844cb866dea1b5e8408df31"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.5/kubectl-del-namespace_0.0.5_darwin_amd64.tar.gz"
      sha256 "8c2930a97486d0aace558987d9c2d3bfac74776a92682cd9042534f4301bf802"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.5/kubectl-del-namespace_0.0.5_linux_arm64.tar.gz"
      sha256 "bebe009986fb8a948b119c28afcf0af8a87b4af1612ab815419d7649c5727ce6"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.5/kubectl-del-namespace_0.0.5_linux_amd64.tar.gz"
      sha256 "bfacf81efc14bf1fe293a361c7f0266796505802667540aa193fa1b912f81b90"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
  end

  test do
    system "#{bin}/kubectl-del_namespace -h"
  end
end
