# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlDelNamespace < Formula
  desc "kubectl plugin to forcefully delete a kubernetes namespace"
  homepage "https://github.com/DoodleScheduling/kubectl-del-namespace"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.3/kubectl-del-namespace_0.0.3_darwin_amd64.tar.gz"
      sha256 "c147cc16cf3922978accdbcfe124fafe3a3db0d27b437384c9d1c4bcb878c2ed"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.3/kubectl-del-namespace_0.0.3_darwin_arm64.tar.gz"
      sha256 "c902b099f63236b84d1fbbbee92df8274abd7242692055ce8521ac900f34d002"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.3/kubectl-del-namespace_0.0.3_linux_arm64.tar.gz"
      sha256 "10bb9dc7e78d01eceaedcbc7fc41082d316d9c9c5a03ffcec2468c6087b2f05e"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DoodleScheduling/kubectl-del-namespace/releases/download/v0.0.3/kubectl-del-namespace_0.0.3_linux_amd64.tar.gz"
      sha256 "bcaba21a384b915a6f23147958ffbbb6bd7dba844127449beafb25cbe48aceae"

      def install
        bin.install "kubectl-del_namespace"
      end
    end
  end

  test do
    system "#{bin}/kubectl-del_namespace -h"
  end
end
